baseURL = 'https://andy9t7.github.io'
languageCode = 'en-us'
title = 'andys portfolioâœŒ'
theme = 'cactus'
enableEmoji = true

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[params]
# Description
description = "Hi! My name is Andy Huynh. I am a PhD student who is currently doing research in computer simulations and computations of the human brain. I enjoy academic teaching and find it rewarding to help students understand difficult concepts and topics in Mechanical Engineering. I do many personal side projects alongside my research (i often get side-tracked from what i am supposed to do ðŸ˜­) which I will be updating on my website."

# Posts
mainSection = "posts"
showAllPostsOnHomePage = false
postsOnHomePage = 5

# Projects
showProjectsList = true
projectsUrl = "https://github.com/andy9t7"

# Social Media
[[params.social]]
  name = "github"
  link = "https://github.com/andy9t7"

[[params.social]]
  name = "email"
  link = "andy.huynh@research.uwa.edu.au" # no need for "mailto:" at the start

[[params.social]]
  name = "linkedin"
  link = "https://www.linkedin.com/in/andythuynhwa/"